// Every Persona in Persona 3 Reload, including the Persona 4 and Persona 5 DLC sets.
// Source: aqiu384/megaten-fusion-tool (src/app/p3r/data/demon-data.json).
// Fields: level, name, arcana, cost, and optionally dlc. Levels may repeat.
// Summon cost changes with each Persona's stats and skills, so cost starts blank ("-------").
window.COMPENDIUM_ENTRIES = [
  { level: 91, name: "Messiah", arcana: "Judgement", cost: "-------" },
  { level: 91, name: "Orpheus Telos", arcana: "Fool", cost: "-------" },
  { level: 89, name: "Lucifer", arcana: "Judgement", cost: "-------" },
  { level: 89, name: "Satanael", arcana: "Fool", cost: "-------", dlc: true },
  { level: 88, name: "Helel", arcana: "Star", cost: "-------" },
  { level: 87, name: "Metatron", arcana: "Aeon", cost: "-------" },
  { level: 86, name: "Chi You", arcana: "Tower", cost: "-------" },
  { level: 85, name: "Asura", arcana: "Sun", cost: "-------" },
  { level: 84, name: "Alilat", arcana: "Empress", cost: "-------" },
  { level: 82, name: "Satan", arcana: "Judgement", cost: "-------" },
  { level: 82, name: "Shiva", arcana: "Tower", cost: "-------" },
  { level: 81, name: "Beelzebub", arcana: "Devil", cost: "-------" },
  { level: 80, name: "Sandalphon", arcana: "Moon", cost: "-------" },
  { level: 79, name: "Masakado", arcana: "Tower", cost: "-------" },
  { level: 78, name: "Thanatos", arcana: "Death", cost: "-------" },
  { level: 78, name: "Vishnu", arcana: "Sun", cost: "-------" },
  { level: 77, name: "Mother Harlot", arcana: "Empress", cost: "-------" },
  { level: 77, name: "Susano-o", arcana: "Fool", cost: "-------" },
  { level: 76, name: "Abaddon", arcana: "Devil", cost: "-------" },
  { level: 76, name: "Saturnus", arcana: "Star", cost: "-------" },
  { level: 75, name: "Mara", arcana: "Tower", cost: "-------" },
  { level: 75, name: "Scathach", arcana: "Priestess", cost: "-------" },
  { level: 74, name: "Futsunushi", arcana: "Magician", cost: "-------" },
  { level: 74, name: "Odin", arcana: "Emperor", cost: "-------" },
  { level: 73, name: "Ananta", arcana: "Aeon", cost: "-------" },
  { level: 73, name: "Attis", arcana: "Hanged Man", cost: "-------" },
  { level: 73, name: "Lakshmi", arcana: "Fortune", cost: "-------" },
  { level: 72, name: "Atavaka", arcana: "Strength", cost: "-------" },
  { level: 72, name: "Baal Zebul", arcana: "Moon", cost: "-------" },
  { level: 71, name: "Kohryu", arcana: "Hierophant", cost: "-------" },
  { level: 71, name: "Yurlungur", arcana: "Temperance", cost: "-------" },
  { level: 70, name: "Houou", arcana: "Star", cost: "-------" },
  { level: 70, name: "Michael", arcana: "Judgement", cost: "-------" },
  { level: 69, name: "Loki", arcana: "Fool", cost: "-------" },
  { level: 68, name: "Alice", arcana: "Death", cost: "-------" },
  { level: 68, name: "Arahabaki", arcana: "Hermit", cost: "-------" },
  { level: 68, name: "Skadi", arcana: "Empress", cost: "-------" },
  { level: 67, name: "Cybele", arcana: "Lovers", cost: "-------" },
  { level: 67, name: "Horus", arcana: "Sun", cost: "-------" },
  { level: 67, name: "Qitian Dasheng", arcana: "Tower", cost: "-------" },
  { level: 66, name: "Melchizedek", arcana: "Justice", cost: "-------" },
  { level: 65, name: "Hell Biker", arcana: "Hanged Man", cost: "-------" },
  { level: 65, name: "Lilith", arcana: "Devil", cost: "-------" },
  { level: 65, name: "Norn", arcana: "Fortune", cost: "-------" },
  { level: 64, name: "Garuda", arcana: "Star", cost: "-------" },
  { level: 64, name: "Thor", arcana: "Chariot", cost: "-------" },
  { level: 63, name: "Barong", arcana: "Emperor", cost: "-------" },
  { level: 63, name: "Byakko", arcana: "Temperance", cost: "-------" },
  { level: 63, name: "Kali", arcana: "Strength", cost: "-------" },
  { level: 62, name: "Gabriel", arcana: "Empress", cost: "-------" },
  { level: 62, name: "Seth", arcana: "Moon", cost: "-------" },
  { level: 61, name: "Kikuri-Hime", arcana: "Priestess", cost: "-------" },
  { level: 61, name: "Kumbhanda", arcana: "Hermit", cost: "-------" },
  { level: 60, name: "Bishamonten", arcana: "Tower", cost: "-------" },
  { level: 60, name: "Loki", arcana: "Justice", cost: "-------", dlc: true },
  { level: 60, name: "Raphael", arcana: "Lovers", cost: "-------" },
  { level: 60, name: "Surt", arcana: "Magician", cost: "-------" },
  { level: 59, name: "Daisoujou", arcana: "Hierophant", cost: "-------" },
  { level: 59, name: "Trumpeter", arcana: "Judgement", cost: "-------" },
  { level: 58, name: "Mot", arcana: "Death", cost: "-------" },
  { level: 58, name: "Vanadis", arcana: "Star", cost: "-------", dlc: true },
  { level: 57, name: "Mada", arcana: "Hanged Man", cost: "-------" },
  { level: 57, name: "Uriel", arcana: "Aeon", cost: "-------" },
  { level: 56, name: "Atropos", arcana: "Fortune", cost: "-------" },
  { level: 56, name: "Chernobog", arcana: "Moon", cost: "-------" },
  { level: 56, name: "Pazuzu", arcana: "Devil", cost: "-------" },
  { level: 55, name: "Jatayu", arcana: "Sun", cost: "-------" },
  { level: 55, name: "Suzaku", arcana: "Temperance", cost: "-------" },
  { level: 54, name: "Astarte", arcana: "Empress", cost: "-------", dlc: true },
  { level: 54, name: "Decarabia", arcana: "Fool", cost: "-------" },
  { level: 54, name: "Siegfried", arcana: "Strength", cost: "-------" },
  { level: 53, name: "Anat", arcana: "Priestess", cost: "-------", dlc: true },
  { level: 53, name: "Belphegor", arcana: "Emperor", cost: "-------" },
  { level: 52, name: "Koumokuten", arcana: "Chariot", cost: "-------" },
  { level: 52, name: "Nebiros", arcana: "Hermit", cost: "-------" },
  { level: 52, name: "Throne", arcana: "Justice", cost: "-------" },
  { level: 51, name: "Ganesha", arcana: "Star", cost: "-------" },
  { level: 50, name: "Magatsu-Izanagi", arcana: "Tower", cost: "-------", dlc: true },
  { level: 50, name: "Rangda", arcana: "Magician", cost: "-------" },
  { level: 49, name: "Dionysus", arcana: "Moon", cost: "-------" },
  { level: 49, name: "Titania", arcana: "Lovers", cost: "-------" },
  { level: 48, name: "Hariti", arcana: "Empress", cost: "-------" },
  { level: 48, name: "Mishaguji", arcana: "Hierophant", cost: "-------" },
  { level: 48, name: "Parvati", arcana: "Priestess", cost: "-------" },
  { level: 47, name: "Hecatoncheires", arcana: "Hanged Man", cost: "-------" },
  { level: 47, name: "Kamu Susano-o", arcana: "Emperor", cost: "-------", dlc: true },
  { level: 47, name: "Nidhoggr", arcana: "Aeon", cost: "-------" },
  { level: 47, name: "Succubus", arcana: "Devil", cost: "-------" },
  { level: 46, name: "Izanagi", arcana: "Fool", cost: "-------", dlc: true },
  { level: 46, name: "Kurama Tengu", arcana: "Hermit", cost: "-------" },
  { level: 46, name: "White Rider", arcana: "Strength", cost: "-------" },
  { level: 45, name: "Quetzalcoatl", arcana: "Sun", cost: "-------" },
  { level: 45, name: "Shiki-Ouji", arcana: "Chariot", cost: "-------" },
  { level: 44, name: "Lachesis", arcana: "Fortune", cost: "-------" },
  { level: 44, name: "Okuninushi", arcana: "Temperance", cost: "-------" },
  { level: 43, name: "Mercurius", arcana: "Magician", cost: "-------", dlc: true },
  { level: 43, name: "Naga Raja", arcana: "Emperor", cost: "-------" },
  { level: 42, name: "Dominion", arcana: "Justice", cost: "-------" },
  { level: 42, name: "Hecate", arcana: "Lovers", cost: "-------", dlc: true },
  { level: 42, name: "Kaiwan", arcana: "Star", cost: "-------" },
  { level: 41, name: "Ganga", arcana: "Priestess", cost: "-------" },
  { level: 41, name: "Ose", arcana: "Fool", cost: "-------" },
  { level: 41, name: "Samael", arcana: "Death", cost: "-------" },
  { level: 40, name: "Anubis", arcana: "Judgement", cost: "-------" },
  { level: 40, name: "Cu Chulainn", arcana: "Tower", cost: "-------" },
  { level: 40, name: "Seiten Taisei", arcana: "Chariot", cost: "-------", dlc: true },
  { level: 40, name: "Thoth", arcana: "Hierophant", cost: "-------" },
  { level: 39, name: "Girimekhala", arcana: "Moon", cost: "-------" },
  { level: 39, name: "Orobas", arcana: "Magician", cost: "-------" },
  { level: 38, name: "Dakini", arcana: "Hermit", cost: "-------" },
  { level: 38, name: "Seiryu", arcana: "Temperance", cost: "-------" },
  { level: 38, name: "Vasuki", arcana: "Hanged Man", cost: "-------" },
  { level: 37, name: "Black Frost", arcana: "Fool", cost: "-------" },
  { level: 37, name: "Clotho", arcana: "Fortune", cost: "-------" },
  { level: 37, name: "Incubus", arcana: "Devil", cost: "-------" },
  { level: 37, name: "Robin Hood", arcana: "Justice", cost: "-------", dlc: true },
  { level: 36, name: "Cendrillon", arcana: "Star", cost: "-------", dlc: true },
  { level: 36, name: "Hanuman", arcana: "Strength", cost: "-------" },
  { level: 36, name: "Milady", arcana: "Empress", cost: "-------", dlc: true },
  { level: 36, name: "Saki Mitama", arcana: "Lovers", cost: "-------" },
  { level: 35, name: "Thunderbird", arcana: "Sun", cost: "-------" },
  { level: 34, name: "Kaguya", arcana: "Moon", cost: "-------", dlc: true },
  { level: 34, name: "King Frost", arcana: "Emperor", cost: "-------" },
  { level: 33, name: "Flauros", arcana: "Hierophant", cost: "-------" },
  { level: 33, name: "Loa", arcana: "Death", cost: "-------" },
  { level: 32, name: "Sarasvati", arcana: "Priestess", cost: "-------" },
  { level: 32, name: "Virtue", arcana: "Justice", cost: "-------" },
  { level: 32, name: "Yakshini", arcana: "Empress", cost: "-------" },
  { level: 31, name: "Eligor", arcana: "Tower", cost: "-------" },
  { level: 31, name: "Mothman", arcana: "Hermit", cost: "-------" },
  { level: 31, name: "Oni", arcana: "Chariot", cost: "-------" },
  { level: 30, name: "Baphomet", arcana: "Devil", cost: "-------" },
  { level: 30, name: "Genbu", arcana: "Temperance", cost: "-------" },
  { level: 29, name: "Jikokuten", arcana: "Strength", cost: "-------" },
  { level: 29, name: "Sati", arcana: "Magician", cost: "-------" },
  { level: 29, name: "Setanta", arcana: "Star", cost: "-------" },
  { level: 28, name: "Johanna", arcana: "Priestess", cost: "-------", dlc: true },
  { level: 28, name: "Kushi Mitama", arcana: "Fortune", cost: "-------" },
  { level: 28, name: "Queen Medb", arcana: "Lovers", cost: "-------" },
  { level: 27, name: "Goemon", arcana: "Emperor", cost: "-------", dlc: true },
  { level: 27, name: "Orthrus", arcana: "Hanged Man", cost: "-------" },
  { level: 26, name: "Legion", arcana: "Fool", cost: "-------" },
  { level: 25, name: "Lamia", arcana: "Hermit", cost: "-------" },
  { level: 25, name: "Power", arcana: "Justice", cost: "-------" },
  { level: 25, name: "Yamata-no-Orochi", arcana: "Moon", cost: "-------" },
  { level: 24, name: "Mithras", arcana: "Chariot", cost: "-------" },
  { level: 24, name: "Yatagarasu", arcana: "Sun", cost: "-------" },
  { level: 23, name: "Arsene", arcana: "Fool", cost: "-------", dlc: true },
  { level: 23, name: "Narcissus", arcana: "Lovers", cost: "-------" },
  { level: 23, name: "Pale Rider", arcana: "Death", cost: "-------" },
  { level: 23, name: "Shiisaa", arcana: "Hierophant", cost: "-------" },
  { level: 23, name: "Take-Mikazuchi", arcana: "Emperor", cost: "-------" },
  { level: 22, name: "Matador", arcana: "Strength", cost: "-------" },
  { level: 22, name: "Mitra", arcana: "Temperance", cost: "-------" },
  { level: 22, name: "Zorro", arcana: "Magician", cost: "-------", dlc: true },
  { level: 21, name: "Leanan Sidhe", arcana: "Empress", cost: "-------" },
  { level: 20, name: "High Pixie", arcana: "Priestess", cost: "-------" },
  { level: 20, name: "Sandman", arcana: "Fortune", cost: "-------" },
  { level: 20, name: "Take-Minakata", arcana: "Hanged Man", cost: "-------" },
  { level: 19, name: "Carmen", arcana: "Lovers", cost: "-------", dlc: true },
  { level: 19, name: "Hua Po", arcana: "Magician", cost: "-------" },
  { level: 18, name: "Captain Kidd", arcana: "Chariot", cost: "-------", dlc: true },
  { level: 18, name: "Mokoi", arcana: "Devil", cost: "-------" },
  { level: 17, name: "Naga", arcana: "Hermit", cost: "-------" },
  { level: 17, name: "Neko Shogun", arcana: "Star", cost: "-------" },
  { level: 16, name: "Oberon", arcana: "Emperor", cost: "-------" },
  { level: 16, name: "Principality", arcana: "Justice", cost: "-------" },
  { level: 15, name: "Fortuna", arcana: "Fortune", cost: "-------" },
  { level: 15, name: "Jack-o'-Lantern", arcana: "Magician", cost: "-------" },
  { level: 15, name: "Pisaca", arcana: "Death", cost: "-------" },
  { level: 15, name: "Rakshasa", arcana: "Strength", cost: "-------" },
  { level: 14, name: "Gurulu", arcana: "Moon", cost: "-------" },
  { level: 14, name: "Zouchouten", arcana: "Chariot", cost: "-------" },
  { level: 13, name: "Berith", arcana: "Hierophant", cost: "-------" },
  { level: 13, name: "Tam Lin", arcana: "Lovers", cost: "-------" },
  { level: 12, name: "Nigi Mitama", arcana: "Temperance", cost: "-------" },
  { level: 12, name: "Slime", arcana: "Fool", cost: "-------" },
  { level: 11, name: "Unicorn", arcana: "Priestess", cost: "-------" },
  { level: 10, name: "Archangel", arcana: "Justice", cost: "-------" },
  { level: 10, name: "Inugami", arcana: "Hanged Man", cost: "-------" },
  { level: 10, name: "Valkyrie", arcana: "Strength", cost: "-------" },
  { level: 9, name: "Chimera", arcana: "Chariot", cost: "-------" },
  { level: 8, name: "Jack Frost", arcana: "Magician", cost: "-------" },
  { level: 8, name: "Lilim", arcana: "Devil", cost: "-------" },
  { level: 8, name: "Onmoraki", arcana: "Hermit", cost: "-------" },
  { level: 7, name: "Forneus", arcana: "Emperor", cost: "-------" },
  { level: 7, name: "Omoikane", arcana: "Hierophant", cost: "-------" },
  { level: 6, name: "Ara Mitama", arcana: "Chariot", cost: "-------" },
  { level: 5, name: "Silky", arcana: "Lovers", cost: "-------" },
  { level: 4, name: "Angel", arcana: "Justice", cost: "-------" },
  { level: 3, name: "Nekomata", arcana: "Magician", cost: "-------" },
  { level: 2, name: "Apsaras", arcana: "Priestess", cost: "-------" },
  { level: 2, name: "Pixie", arcana: "Lovers", cost: "-------" },
  { level: 1, name: "Orpheus", arcana: "Fool", cost: "-------" },
];
